<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="USHYDSHMURAL5" name="com.DEvents.tests.TestAPI_GetParticipants_demo" tests="6" failures="0" timestamp="2019-11-20T19:29:41 IST" time="21.332" errors="1">
  <testcase name="checkResponseBody" time="21.322" classname="com.DEvents.tests.TestAPI_GetParticipants_demo">
    <error type="java.lang.IllegalStateException" message="DB hit failed.">
      <![CDATA[java.lang.IllegalStateException: DB hit failed.
at com.DEvents.coreFramework.DBConnectivity.dbResultSet2xlsx(DBConnectivity.java:164)
at com.DEvents.tests.TestAPI_GetParticipants_demo.checkResponseBody(TestAPI_GetParticipants_demo.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.001" classname="com.DEvents.tests.TestAPI_GetParticipants_demo"/>
  <testcase name="validateJSONSchema" time="0.007" classname="com.DEvents.tests.TestAPI_GetParticipants_demo"/>
  <testcase name="checkContentEncoding" time="0.001" classname="com.DEvents.tests.TestAPI_GetParticipants_demo"/>
  <testcase name="checkContentType" time="0.000" classname="com.DEvents.tests.TestAPI_GetParticipants_demo"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.DEvents.tests.TestAPI_GetParticipants_demo"/>
</testsuite> <!-- com.DEvents.tests.TestAPI_GetParticipants_demo -->
